<div id="topo" class="sobre">
<nav class="container">
<div id="menuwrapper">
<ul id="p7menubar">
<li class="principal"><a href="ingles.php">HOME</a></li>
<li class="principal"><a class="trigger">WITH RUY</a>
	<ul class="montagem">
		<li><a href="ruy_guerra.php?idioma=3">About Ruy</a></li>
		<li><a href="cronologia.php?idioma=3">Chronology</a></li>
		<li><a href="teses.php?idioma=3">Works on Ruy</a></li>
		<li><a href="noticias.php?idioma=3">News</a></li>
		<li><a href="acervo.php?idioma=3">Collection</a></li>
	</ul>
</li>
<li class="principal"><a class="trigger">FILMOGRAPHY</a>
	<ul class="montagem">
		<li><a href="longas.php?idioma=3">Full lenght films</a></li>
		<li><a href="curtas.php?idioma=3">Short films</a></li>
		<li><a href="entrevistas.php?idioma=3">Interviews</a></li>
		<li><a href="ator.php?idioma=3">Actor</a></li>
		<li><a href="roteirista.php?idioma=3">Scriptwriter</a></li>
		<li><a href="montador.php?idioma=3">Editor</a></li>
		<li><a href="festivais.php?idioma=3">Festivals/Prizes</a></li>
	</ul>
</li>
<li class="principal"><a href="teatro.php?idioma=3">THEATER</a></li>
<li class="principal"><a href="poesias.php?idioma=3">POETRY</a></li>
<li class="principal"><a class="trigger">PROSE</a>
	<ul class="montagem">
		<li><a href="cronicas.php?idioma=3">Chronicles</a></li>
		<li><a href="contos.php?idioma=3">Short Stories</a></li>
		<li><a href="prefacios.php?idioma=3">Forewords</a></li>
	</ul>
</li>
<li class="principal"><a href="musicas.php?idioma=3">LYRICS</a></li>
<li class="principal"><a href="pelo_mundo.php?idioma=3">GLOBETROTTER</a></li>
<li class="principal"><a href="oficinas.php?idioma=3">OFICINAS</a></li>
<li class="principal"><a class="trigger">CONTACT</a>
	<ul class="montagem">
		<li><a href="contato.php?idioma=3">Contact</a></li>
		<li><a href="site.php?idioma=3">Website</a></li>
	</ul>
</li>
<li class="principal"><a href="index.php"><img class="pais" src="images/brasil.gif" alt="português" /></a></li>
<li class="principal"><a href="frances.php?idioma=2"><img class="pais" src="images/franca.gif" alt="francês" /></a></li>
</ul>
<br class="all" />
</div>
<div id="menuCel"><a href="menu-eng.html">MENU</a></div>
</nav>
<div class="cortina">
<img class="nada" src="images/bandoc-6.png" alt="" /><br class="clearit" />
</div>
</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53600587-1', 'auto');
  ga('send', 'pageview');

</script>