<div id="topo" class="sobre">
<nav class="container">
<div id="menuwrapper">
<ul id="p7menubar">
<li class="principal"><a href="index.php">HOME</a></li>
<li class="principal"><a class="trigger">COM O RUY</a>
	<ul class="montagem">
		<li><a href="ruy_guerra.php">Quem é Ruy</a></li>
		<li><a href="cronologia.php">Cronologia</a></li>
		<li><a href="teses.php">Trabalhos sobre</a></li>
		<li><a href="noticias.php">Notícias</a></li>
		<li><a href="acervo.php">Acervo</a></li>
	</ul>
</li>
<li class="principal"><a class="trigger">FILMOGRAFIA</a>
	<ul class="montagem">
		<li><a href="longas.php">Longas</a></li>
		<li><a href="curtas.php">Curtas</a></li>
		<li><a href="entrevistas.php">Entrevistas</a></li>
		<li><a href="ator.php">Ator</a></li>
		<li><a href="roteirista.php">Roteirista</a></li>
		<li><a href="montador.php">Montador</a></li>
		<li><a href="festivais.php">Festivais e Premiações</a></li>
	</ul>
</li>
<li class="principal"><a href="teatro.php">TEATRO</a></li>
<li class="principal"><a href="poesias.php">POESIA</a></li>
<li class="principal"><a class="trigger">PROSA</a>
	<ul class="montagem">
		<li><a href="cronicas.php">Crônicas</a></li>
		<li><a href="contos.php">Contos</a></li>
		<li><a href="prefacios.php">Falas e Prefácios</a></li>
	</ul>
</li>
<li class="principal"><a href="musicas.php">LETRAS DE MÚSICA</a></li>
<li class="principal"><a href="pelo_mundo.php">GLOBETROTTER</a></li>
<li class="principal"><a href="oficinas.php">OFICINAS</a></li>
<li class="principal"><a class="trigger">CONTATO</a>
	<ul class="montagem">
		<li><a href="contato.php">Contato</a></li>
		<li><a href="site.php">O Site</a></li>
	</ul>
</li>
<li class="principal"><a href="frances.php"><img class="pais" src="images/franca.gif" alt="francês" /></a></li>
<li class="principal"><a href="ingles.php"><img class="pais" src="images/eua.gif" alt="inglês" /></a></li>
</ul>
<br class="all" />
</div>
<div id="menuCel"><a href="menu.html">MENU</a></div>
</nav>
<div class="cortina">
<img class="nada" src="images/bandoc-6.png" alt="" /><br class="clearit" />
</div>
</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53600587-1', 'auto');
  ga('send', 'pageview');

</script>