<!DOCTYPE html>
<html lang="pt-br">
<head><meta http-equiv="Last-Modified" content="Sun, 07 Sep 2014 10:10:10 GMT">
<meta http-equiv="content-type" content="text/html;charset=windows-1252" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=3" />
<meta name="robots" content="index,follow" />
<link href="geral.css" rel="stylesheet" type="text/css">
<link href="interna.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="js_home39.js"></script>
<title>Quem é Ruy Guerra</title>
<body>

<section class="conteudo">
	<br />
	<img class="ruy" src="images/ruy_guerra.png" alt="Ruy Guerra" title="Ruy Guerra" /><img class="tituloCategoriaV2" src="images/ruyguerrav.jpg" alt="a vida de Ruy Guerra" title="a vida de Ruy Guerra" />
	<br class="all" /><br /><br />
	
<?php
$idioma = $_GET["idioma"];

if ($idioma == 3) {
	
echo <<< EOT
<p class="basico">Ruy Guerra is a well- known name to cinema fans. In the 1960s, the period of the Cinema Novo, renewing Brazilian cinema, Ruy, born in Mozambique, arrived in Rio de Janeiro, direct from Paris, where he had graduated in Film Making. Today he is one of the surviving myths of the Cinema Novo, indeed one the most famous, having been the first of the group to shoot films outside Brazil. He is also known to those who enjoy Brazilian popular music from the 1960s and 70s, when he partnered young musicians. In 1958 Ruy came to Rio de Janeiro, which has been his safe haven until today. The trip to Brazil was a desire expressed years earlier in letters to his father, brother and friends.</p>
<p class="basico">At the moment (August 2014) he is a well-lived 83 years-old, whose energy makes those of us who are much younger envy him. Many say that this energy comes from his home country, Mozambique, on the edge of the Indian Ocean in southern Africa. He is the son of a Portuguese couple who were trying life in the Portuguese colony and who settled in the capital, Lourenço Marques, and started a family. Since he was ten Ruy has been crazy about writing, film and film making, and during the second half of the 1940s he published short stories, articles and poetry in newspapers and even today repeatedly talks about his frustrated vocation as a writer, reaffirming his desire to write a novel. The complicated situation of living financially from film making also led him to direct the concerts of his friends, and he also wrote the play “Calabar: in praise of treason” in partnership with Chico Buarque. It was banned on the eve of the premiere, causing financial losses to the producers. Like many contemporaries, Chico Buarque and Ruy Guerra often had problems with the lyrics.</p>
<p class="basico">Since his teens Ruy has understood filmmaking as a way of thinking and presenting political and social relations. Lourenço Marques was the most important port on the Indian Ocean in Southern Africa, and much of the south of the continent\'s trade passed through the port. At 16, with an 8 mm. camera borrowed from a friend, he filmed the reality of the Cais Gorjão harbour, portraying the lives of black workers. He filmed them resting under wagons, eating, sleeping under trains; for Ruy for these images “reminded me of concentration camps”. According to one analyst, Ruy as an amateur film maker, “flirted with social critique”.</p>

<p class="imagem">
	<img class="img480" src="images/ruy_guerra-por_lara.jpg" alt="A photo of Ruy In Mozambique sent by his sister Lara" title="A photo of Ruy In Mozambique sent by his sister Lara" />
	<br class="all" />
	A photo of Ruy In Mozambique sent by his sister Lara 
</p>

<p class="basico">In the family home and the Liceu Salazar state secondary school, Ruy received a Portuguese education. He and his classmates were educated by teachers “banished from Portugal by the Dictatorship”, “critical thinkers” who made them read a lot, resulting in many students becoming rebels against the status quo. They refused to accept the cultural production of the Salazar dictatorship, and Brazilian cultural material was very important, not only because Brazil was a former Portuguese colony that had become independent, but also because of the similarities between the cultures of Mozambique and Brazil (the climate, the presence of black people, the aromas and flavours...). Brazilian literature and magazines, which were were often censored and had to enter the country illegally, impressed this generation, called the Mozambique “diaspora”. Ruy stated in an interview: “Some of us made up a generation that mostly left the country and distinguished itself in the arts, philosophy (...) because of the political and social context in which they were born and raised (...) it was not by chance or just as a result of individual psychological conditions”. This generation used culture as their form of political revolt against colonialism and racism. Ruy, concerned with the relations of domination and subordination in the colony, was interrogated and arrested by the police of the Portuguese dictatorship because of his independent thinking at the Liceu, and because of his activities and those of his group he was eventually legally prevented from visiting Portugal for a number of years.</p>
<p class="basico">At 20 he went to study film in Paris and arrived in the French capital at a very important moment for cinema as young filmmakers were trying to impose their auteur style on the traditional large-scale industry. He professionally graduated during this period, the early 1950s, when the traditional cinema was being renewed, with the first ripples of the Nouvelle Vague. He recalls the movement as being made up of young French intellectuals to whom he, as a foreign immigrant, felt very different: “[The Nouvelle Vague] always had a clear right-wing position and I […] was definitely on the left [...] I condemned French intellectuals for their lack of political engagement, they never talked about the war in Algeria or about immigrants”. He attended the Institut des Hautes Études Cinématographiques (IDHEC) and was seen by classmates as an excellent student, better educated than others, though a permanent questioner. He also studied acting for two years on a course at the Théâtre National de Paris (NPT).</p>
<p class="basico">In Paris he got to know Brazilians, with whom he came to try his chance in the New World which he hoped to conquer through his enthusiasm for film. He carried in his luggage the first script he wrote shortly after graduating and which he had been attempting in many ways to film in the Old World. This script would later become “Os Fuzis” [The Guns], which won the Silver Bear at the Berlin Film Festival in 1964 and was one of the most remarkable films of that period.</p>

<p class="imagem">
	<img class="img800" src="images/cinema-novo_grupo.jpg" alt="Cinema Novo in Brazil - Meeting of filmmakers for a the French TV programme, “Carnets brésiliens”, Copacabana 1966" title="Cinema Novo in Brazil - Meeting of filmmakers for a the French TV programme, “Carnets brésiliens”, Copacabana 1966" />
	<br class="all" />
	Meeting of filmmakers for a the French TV programme, “Carnets brésiliens”, Copacabana 1966
</p>

<p class="basico">Ruy jokes that he was born as a filmmaker with the Cinema Novo but he was not born into it, among the young people between whom, despite the usual rivalries and clashes, there was a close cooperation on the basis of the films they made. It was a cinema search of identity: “We were interested in producing films that portrayed the reality of the people, political and social conflicts, to escape the production rules and dogmas of the aesthetics of the industrial cinema”. However, Ruy did not practice the art as weapon of revolutionary propaganda; his filmography can hardly be seen as didactic but was rather part of a generation which, in the 1960s, wished to change the world to what they believed was the best for society; and also, for some of them, including Ruy, their daily lives.</p>
<p class="basico">Over the years, Ruy has worked in various functions related to the screen (photographer, assistant director, director, screenwriter, actor, editor, executive producer, executive and artistic director and teacher), in writing poetry, lyrics, and newspaper columns, shows and plays (which he sometimes also directed). He recently declared himself “a typical artist produced by underdevelopment”, who has had to work in various forms of art in order to survive. He has used all his gifts with words; in addition to writing poems, lyrics, he wrote and directed plays, and for five years penned a weekly column in the Cadernos Dois supplement of the O Estado de São Paulo newspaper.</p>
<p class="basico">Economic difficulties, an inherent part of the Brazilian authorial cinema, led him for a time to live from writing lyrics in the Zona Sul in Rio de Janeiro for musician friends such as Sergio Ricardo, Edu Lobo, Chico Buarque de Holanda, Francis Hime, Carlos Lyra, Luiz Eça and Milton Nascimento. A talented writer of lyrics, he has written more than a hundred songs, which abandoned the contents of the “the little boat and the flower” of the Bossa Nova for a stronger social theme and content. The difficulty of living from his films also led to work with the theatre, directing the concerts of his friends and, when invited, he also directed a number of plays. He also wrote in partnership with Chico Buarque “Calabar: in praise of treason”, which was banned by the censorship of the military dictatorship. Like many others, Chico Buarque and Ruy often had various problems with the lyrics.</p>
<p class="basico">Ruy is very proud of being classified as a political filmmaker. Since his adolescence he has been a politician a broad sense: being involved with the problems of his time. He repeatedly says: “I look at reality from a political and cultural point of view.” Throughout his life Ruy has taken this political position with a capital P, though never having been an activist or member of a political party. Ruy sees himself and is seen as a man of the left from the way he speaks and lives, and his art and teaching. He believes all aesthetics are political, as they will always contain a worldview and will be anchored to a set of values they present, defend or condemn. In 1997, the film critic Maria do Rosario Caetano noted that he retained the “highly political rhetoric of the 1960s” and did not believe in the end of ideology; and in recent speeches and writings Ruy seems to confirm this.</p>
<p class="basico">From 1960 to 1970 Ruy worked in France on a number of occasions in film and television. He was close to the group linked to film magazine Positif. In 1965 the French magazine Cahiers de Cinema, which gave great prominence to the Brazilian Cinema Novo, summarized the themes of his films: cruelty, violence, racism, never-ending time... According to Ruy, “Whoever analyses my films has said that there is a kind of obsession for the areas of power and repressive mechanisms, whether in the family environment, social structures or government.”</p>
<p class="basico">The socialist revolution of the new People\'s Republic of Mozambique, victorious in 1975 under the leadership of Samora Machel, initially gave a fundamental role to film in the construction of national identity. It was an important part of the attempt to unite many tribes, whose culture is based on oral tradition, into a nation. Urged by former friends, who now had posts in the government, Ruy started to actively collaborate in the creation of the National Film Institute of Mozambique (INC) and the training of film technicians; he gave practical lessons and brought to Maputo (formerly Lourenço Marques) many experts in various aspects of film. He intensely lived the experience of independence and decolonization of the country where he was born; his African films are by their nature political.</p>
<p class="basico">His left-wing position is also clear in his relations with Cuba, where he lived for various periods. Since the beginning of the International Festival of New Latin American Cinema in 1979, his films have been shown there. Since 1988 he has been part of the teaching staff of the well-known Escuela Internacional de Cine y TV in San Antonio de Los Baños, 30 kilometres from Havana. He took part in projects and scripts with Gabriel García Márquez, “Gabo”, a founder of the school, who became his personal friend. He was the most important maker of Gabo’s films: “Eréndira”, “Fábula de la bella Palomera”, “Veneno de la Madrugada” and “Me alquilo para soñar” (a mini-series for Spanish television, filmed entirely in Havana). At the end of the 1990s he also made in Havana “Estorvo”, adapted from the novel by Chico Buarque, with the main part played by the Cuban actor Jorge Perrugoria and a team largely made up of Cuban technicians.</p>

<p class="imagem">
	<img class="img800" src="images/com-gabo.jpg" alt="Ruy Guerra and Gabriel García Márquez during the filming of Eréndira, Mexico, 1982" title="Ruy Guerra and Gabriel García Márquez during the filming of Eréndira, Mexico, 1982" />
	<br class="all" />
	Ruy Guerra and Gabriel García Márquez during the filming of “Eréndira”, Mexico, 1982
</p>

<p class="basico">Brazilian and Latin American filmmakers sometimes remain decades without being able to film because they face permanent economic problems and sometimes difficulties due to the political situation. Ruy managed to shoot long, medium and short length films in Brazil, France, Portugal, Spain, Mexico, and Cuba. He has often said: “I didn’t make all the films I wanted to, but I wanted to make all the films that I did make.” At the beginning of the 21st century he was invited to write for the theatre on Don Quixote, creating a musical called “Don Quixote from Nowhere”, an adaptation of Don Quixote to the Northeast of Brazil.</p>
<p class="basico">And when he was unable to film he was involved in teaching, organizing film courses in Rio de Janeiro from the 1990s. His teaching activities in the last 10-12 years have developed into courses, lectures and workshops. In an interview he said: “I say in the first lesson: If you have come here to make a North American film it is easy. Let’s go to the bar, and in an hour, I’ll tell you all you need to know. […] I tell them that it\'s not worth wasting two and a half years to make films like the Americans. Now, if the guy wants to make Brazilian films, he will spend two years in college making an effort, and he will continue making an effort, and will not leave college knowing how to make Brazilian films. It\'s another thing: it’s a quest, it is to make a link with reality; it is to know who you are”. He emphasizes how fundamental it is to “open the heads of young people to the act of thinking about art, cultural education [...] so that a person can take on such a great responsibility [...] for this means of expression that is in my view so vital and important, so politically and aesthetically important.”</p>
<p class="basico">When talking about movies and the market his position is clear: “The equations of society are all poorly made, and you live with these wrong equations. A film does not have to have 10 million viewers. A movie has to be seen by X people who can take from this film something important for their lives. It\'s different. Because of these millions of viewers there are usually not even ten that take from the film something important for their lives. They have consumed the film as a product, as 'fast food'. [...] It is important to see that seeing these American films is the same as eating at Macdonald's. There's no difference. [...] You must be careful, very careful.”</p>
<p class="basico">The study and practice of a cinematic language is constantly renewed in his filmmaking, and Ruy stresses how important this is: “Something fundamental for me is to find structures that break with standard concepts, basically the North American hegemonic structure, which I believe reduces reality and is of no use for our culture. [...]. This refusal, this factor of refusal, I believe, is still present today. Many films are wrong, but I think this is even present in these films that are wrong”.</p>
<p class="basico">He has lived in various countries and different continents and has been called “a citizen of the world”. His path through life cannot be separated from his artistic production, as his artistic quest has been the defining factor of his movements through space and time. He defines himself: “Half African, half Portuguese, half Brazilian, somewhat Latin, half lost, 100% of what in this cocktail of anguishes?”</p>

<p class="imagem">
	<img class="img480" src="images/atacama.jpg" alt="Ruy Guerra no deserto do Atacama" title="Ruy Guerra no deserto do Atacama" />
	<br class="all" />
	Chile, 2014
</p>
EOT;
	
} if ($idioma == 2) {
	
echo <<< EOT
<p class="basico">Ruy Guerra est un nom connu de ceux qui sont intéressés par le cinéma d ´auteur. A l’époque du renouveau du  “Cinema  Novo” brésilien, dans les années 1960,  il  atterri à Rio venant de Paris, où il avait  fait une  formation  de  cinéma. Aujourd’hui, il  est un des mythes survivants du groupe, un des plus célèbres. Il a été  le premier à filmer hors  du Brésil. Ruy  Guerra est arrivé à  Rio de Janeiro en 1958. Depuis cette date, cette ville est devenue son son refuge.Dans ses  ses lettres à son père, son frère et son meilleur ami, il évoquait souvent son souhait de se rendre au Brésil.</p>
<p class="basico">Aujourd’hui-  Août -2014-  à l’âge de  83 ans ,  il a   toujours une énergie débordante. Beaucoup disent que cette force lui vient de son pays d`origine, le Mozambique, aux  bords de l’océan Indien . Il  est le fils d´un couple portugais venu tenter  leur chance  dans cette colonie portugaise.  Très jeune  Ruy  Guerra était passionné  d’écriture et de cinéma. Au cours de la seconde moitié des années 1940, la presse publie  plusieurs de ses contes, articles et poèmes. Aujourd’hui il dit que sa vocation -  constamment frustré – était de devenir écrivain,  et  il réaffirme son désir d’écrire un roman. Depuis l’adolescence Ruy Guerra considère  le cinéma comme une façon de penser les relations politiques et sociales.  Lourenço Marques était le port le plus important en Afrique du Sud. À 16 ans, avec un appareil photo  8 mm,  emprunté à  un ami, Ruy   Guerra  filme le Pier Gorjão : la réalité du port, la vie des travailleurs noirs, ces images  lui rappelaient  “les camps de concentration”.  Un analyste dira sur son œuvre ,  même comme un amateur ,  Ruy Guerra “a flirté avec la critique sociale”.</p>

<p class="imagem">
	<img class="img480" src="images/ruy_guerra-por_lara.jpg" alt="photo de Ruy Guerra au Mozambique" title="photo de Ruy Guerra au Mozambique" />
	<br class="all" />
	Photo de Ruy Guerra au Mozambique
</p>
                      
<p class="basico">Dans le foyer parental et le Lycée Salazar,  l´ école publique qu´il a fréquenté, Ruy Guerra a reçu une éducation européenne-portugaise. Lui et ses collègues ont été formés par des enseignants “bannis du Portugal par la dictature”, qui ont  su développé chez  les élèves,  le goût de la lecture et la pensée critique. Ruy  Guerra faisait partie du groupe qui s´est révolté contre le statu quo. Il refusait la production culturelle portugaise de la dictature de Salazar. Tout ce qui provenait  du Brésil  était très important, non seulement parce que le Brésil était une ancienne colonie portugaise qui avait acquis  son indépendance, mais à cause des similitudes avec la culture et de l’espace brésilien (climat, présence des noirs, des arômes et des saveurs ...). La littérature et les magazines ont été souvent censurés, ils circulaient « sous la table ». Il a fait parti d´une  génération du Mozambique appelée  la «diaspora». Dans une interview, Ruy Guerra  dit :  «Certains d’entre nous  ont fini par constituer une génération qui dans sa majorité à quitté le pays et  ce sont distingués  dans les arts, dans la philosophie (...) en raison du contexte politique et social dans lequel nous sommes nés et dans le quel nous avons grandis (...) et pas seulement par hasard ou du à des conditions psychologiques individuelles. Une partie de cette génération  a utilisé la culture pour se révolter  contre le colonialisme et le racisme. Inquiet des rapports de domination et de subordination dans la colonie, Ruy Guerra  a subi des interrogatoires et des  arrestations.  Un procès   l’a empêchera de retourner au Portugal pendant  quelques années.</p>
<p class="basico">A 20 ans,  il vient  à Paris faire des études  de cinéma. Il y arrive  dans une période très importante du point de vue cinématographique :  des  jeunes cinéastes tentaient d’imposer le “cinéma d’auteur” contre  la grande industrie traditionnelle; les premiers ondulations de la Nouvelle Vague se pointaient.Le mouvement était constitué par de jeunes intellectuels français  qui comme lui,  un immigré étranger, se sentait très différent: «(la Nouvelle Vague) a toujours eu une position de droite  (..) et lui avait une position nettement de gauche  un  apolitisme très politique, ils ne parlaient  jamais de la guerre d’Algérie, des immigrés.</p>
<p class="basico">Il a fait des études  à l’IDHEC (Institut des Hautes Études Cinématographiques); il  était considéré comme un bon élève par ses collègues, plus préparé que d’autres, mais aussi comme un éternel jeune rebelle. Pendant deux  ans il a  fréquenté un cours au Théâtre National de Paris (TNP).</p>
<p class="basico">Dans la capitale française il s´est rapproché  des brésiliens qui l ´ont aidé a tenter sa  chance dans le Nouveau Monde, ce nouveau monde qu´il espérait  atteindre par son enthousiasme et son travail. Il portait dans ses bagages son premier  scénario: les Fuzils ,   íl avait essayé sous différentes formes  de  le mettre en œuvre en Europe ;  finalement ce scénario  aura l’ Ours d’argent au Festival de Berlin en 1964.</p>

<p class="imagem">
	<img class="img800" src="images/cinema-novo_grupo.jpg" alt="Groupe du Cinéma Novo dans un bar à Rio de Janeiro" title="Groupe du Cinéma Novo dans un bar à Rio de Janeiro" />
	<br class="all" />
	Groupe du Cinéma Novo dans un bar à Rio de Janeiro
</p>        

<p class="basico">Il dit  être né  avec le groupe  du Cinéma Novo  mais pas en lui  - malgré les rivalités et les affrontements habituels - il y avait une coopération étroite liée aux  films des nouveaux  cinéastes. C ´était un cinéma  en recherche de l’identité brésilienne: “Nous voulions  produire des films qui décrivaient  la réalité des gens, leurs conflits politiques et sociaux, et fuir les règles et les dogmes de production de l’esthétique industrielle du cinéma”. Ruy  Guerra  n ´a jamais  utilisé  l’art comme une arme de propagande révolutionnaire; sa filmographie ne peut pas  être considérée comme didactique. Il faisait partie d’une génération qui, dans les années 1960,  voulait changer le monde à travers  une société meilleure, une vie...</p>
<p class="basico">Il a exercé  diverses fonctions liées à la toile (photographe, directeur adjoint, directeur, scénariste, acteur, éditeur, producteur exécutif,  directeur artistique ou  enseignant).</p>
<p class="basico">Pendant cinq ans il a écrit une chronique hebdomadaire pour le journal O Estado de S. Paulo. Il s’est récemment déclaré  “un artiste,  produit du sous-développement”,  obligé  à exercer différentes formes d’art pour survivre. Avec les difficultés économiques pour faire des films il a écrit des textes pour les jeunes musiciens de la Zone Sud de Rio, comme Sergio Ricardo, Edu Lobo, Chico Buarque de Holanda, Francis Hime, Carlos Lyra, Luiz Eça et Milton Nascimento. Plus de  100 textes qui ont abandonné les sujets  “du petit bateau et de la fleur” de la Bossa Nova pour   des thèmes plus forts,  avec  contenu social. Il a également dirigé  des pièces de théâtre. Et il a écrit  avec Chico Buarque “Calabar: l’éloge de la trahison”, qui a été interdite par la dictature militaire. Comme beaucoup d’autres, souvent Chico Buarque de Holanda  et Ruy Guerra ont eu beaucoup de problèmes avec les textes  qu´ils écrivaient. </p>
<p class="basico">Souvent classé comme un cinéaste politique, il est très fier que l’on considère comme tel . Depuis son adolescence, il est un homme politique au sens large du mot: il est impliqué dans les problèmes de son temps. Il a dit à plusieurs reprises: «J’ai un regard politique sur la réalité  et d’un point de vue culturel. Tout au long de sa vie Ruy Guerra, il a  arboré  ce positionnement politique avec un grand P, n’ayant jamais été un militant ou membre d’un parti politique. Son discours est celui d’un   homme de gauche , ses attitudes de vie, ses expressions dans le domaine artistique et pédagogique également Pour lui toute position esthétique est politique, elle apporte nécessairement  une vision du monde, elle a un ensemble de valeurs qu’elle représente, défend ou condamne. </p>
<p class="basico">Entre 1960 à 1970,  il a travaillé en France à plusieurs reprises dans des films et à la télévision. En 1965, les Cahiers de Cinéma  et Positif ont donné une grande importance au Cinéma Novo brésilien. Ruy Guerra  a été très proche du groupe des éditeurs de Positif. Les Cahiers ont résumé  les thèmes de ses films: la cruauté, la violence, le racisme, le temps  qui ne s’arrête jamais ... Selon Ruy Guerra « On me  dit que j´ai une sorte d’obsession pour les domaines du pouvoir,  pour les mécanismes de répression, que ce soit dans le milieu familial, dans les structures sociales ou du gouvernement ». </p>
<p class="basico">La révolution socialiste de la nouvelle République populaire du Mozambique, victorieuse en 1975 sous la direction de Samora Machel, a donné dès son début un rôle fondamental à l ´image dans la construction de l’identité nationale, élément important dans la tentative d’unir plusieurs tribus en une seule nation, dont la culture était basée sur la tradition orale. Poussé par d’anciens collègues du gouvernement, Ruy Guerra a collaboré activement à la création de l’Institut National du Film du Mozambique (INC) et à la formation des cadres pour le cinéma; il a fait venir  à Maputo (anciennement Lourenço Marques) de nombreux experts dans diverses activités cinématographiques. Il a vécu profondément  l’expérience de l’indépendance et la décolonisation de sa terre natale; ses films africains sont  nettement politique. </p>
<p class="basico">Sa position à gauche est également claire dans ses relations avec Cuba, où il a vécu pendant certaines périodes. Depuis la création  du Festival International du nouveau cinéma latino-américain en 1979, ses films y sont présentés. A partir de 1988, il  fait partie de la “Escuela Internacional de Cine y TV de San Antonio de Los Baños”, à 30 kilomètres de La Havane, où il a participé à des projets avec son ami   Gabriel Garcia Marquez - Gabo - un des fondateurs de la Escuela. Il a été  le  cinéaste  qui  a fait le plus de films inspirés des romans de García Márquez: Erendira, La Fable da la Belle Palomera, Me alquilo para soñar (mini-série pour la télévision espagnole, entièrement tourné à La Havane) et La Mala Hora.  A la fin de l’année 1990,il fait  un film adapté d’un roman de Chico Buarque, » Embrouille, » ayant comme personnage principal  un acteur cubain Jorge Perrugoria et une équipe formée en grande partie par des techniciens cubains. </p>

<p class="imagem">
	<img class="img800" src="images/com-gabo.jpg" alt="Ruy Guerra avec Gabriel García Márquez pendant le tournage de Erendira" title="Ruy Guerra avec Gabriel García Márquez pendant le tournage de Erendira" />
	<br class="all" />
	Ruy Guerra avec Gabriel García Márquez pendant le tournage de Erendira
</p>


<p class="basico">Les cinéastes brésiliens et latino-américains restent  parfois plusieurs années sans filmer, du aux  difficultés économiques  et parfois en raison de la conjoncture politique. Ruy Guerra  a tourné des films de long, moyen et court métrages au Brésil, en France, au Portugal,  au Mexique, à Cuba. Il a dit à plusieurs reprises : “Je n ’ai pas tourné  tous les films que je voulais, mais je voulais faire tous les films que j’ai tourné.” Au début du XXIème siècle il a été invité à écrire pour le théâtre : il a fait une comédie musicale intitulée Don Quichotte de nulle part, une adaptation de la nature du Nord-Est brésilien.</p>
<p class="basico">Il  enseigne dans écoles  de cinéma à Rio de Janeiro depuis les années 1990. Dans une interview, il a déclaré: «Dans mon premier cours  je dis : Si vous venez ici pour le film américain c ‘est facile, nous allons au café et dans une heure je dirai tout ce que vous devez savoir. “(...) Je leur dis que ce n’est pas la peine de perdre deux ans et demi à faire des films comme les américains. Maintenant, si les gars veulent faire un film brésilien, il passera deux ans à l’université et va  poursuivre... C’est toute une autre chose: c’ est se lier à la réalité, c ´est  savoir qui vous êtes”. Il souligne comme fondamentale “ouvrir les têtes des jeunes à l’acte de penser l’art, l’éducation culturelle (...) pour assumer une responsabilité aussi grande (...) ce moyen d’expression  est à mon avis extrêmement vital et important, politiquement et esthétiquement important”. </p>
<p class="basico">Sur  la position de marché il se positionne clairement: “Les équations de la société sont toutes mal faites et on vit avec ces équations erronées. Un film ne doit pas être fait pour 10 millions de spectateurs. Un film doit être vu par X personnes qui peuvent prendre de  ce film quelque chose d’important pour leurs vies. C’est différent. Parce que entre ces millions de spectateurs il n ´y en a  pas généralement,  dix qui prennent du film quelque chose d’important pour leurs vies. Ils ont utilisé ce film comme un produit, comme un \"fast food\". (...) Il est important de voir que ces films américains sont la même chose qu’ un produit  du Macdonald. Il n’y a aucune différence. (...) Il faut être prudent, très prudent.”</p>
<p class="basico">L’étude et la pratique d’un langage cinématographique est une constante sans cesse renouvelée dans son cinéma: “C´est quelque chose de fondamental pour moi  de trouver des structures qui rompent avec les schémas, les concepts,  la structure hégémonique des États-Unis, qui, je crois,  réduisent  la réalité et ne servent pas  notre culture. (...). Ce refus, le facteur  refus, je pense qu’il est là. Beaucoup de films sont mauvais, mais je pense que cela est présent même dans ces films qui ne sont pas bons. </p>
<p class="basico">Ruy Guerra  a vécu dans trois continents et plusieurs pays ; étant présenté comme "un citoyen du monde". Son parcours de vie n’est pas séparé de sa production artistique,  qui  a été responsable de ses mouvements dans l’espace et de  la continuité de ses activités dans le temps. Il se définie : “moitié africain, moitié portugais, moitié brésilien, un peu latino, un  peu perdu, 100%  quoi, dans ce cocktail d´angoisses»?</p>

<p class="imagem">
	<img class="img480" src="images/atacama.jpg" alt="Ruy Guerra no deserto do Atacama" title="Ruy Guerra no deserto do Atacama" />
	<br class="all" />
	Chile, 2014
</p>
EOT;

} else {

echo <<< EOT
	<p class="basico">Em meados da década de 1970, Ruy Guerra se auto explicava em poema:</p>
	<br />
	                   
	<p class="basicoC"><span class="italico">Vivo sobre um corpo de mulher<br />                                                    
                   que faz de mim gato e sapato<br />  
                  que me foge e me desfolha<br />  
                 e brinca de gato e rato</span></p>
  <p class="basicoC"><span class="italico">Vivo sobre três continentes<br />                                                                            
                   e isso não me contém<br />                                                                               
                   a raiva que trago nos dentes<br /> 
                 não sei se me faz mal ou bem</span></p>
	<p class="basicoC"><span class="italico">Vivo à sombra de um túnel<br />
do outro lado do sol<br />
 e nesta clave difícil<br />
me sustento num bemol</span></p>
<br />

<p class="basico">Ruy Guerra é um nome conhecido para os que se interessam  por cinema. Em tempos renovadores do Cinema Novo, anos 1960,  esse africano desembarcou no Rio de Janeiro direto de Paris, onde se formara cineasta. Hoje é um dos mitos sobreviventes do grupo, dos mais notórios, tendo sido o primeiro deles a filmar fora do Brasil. É também conhecido por quem curte música popular brasileira dos anos 1960/70, quando ele  fez parcerias com jovens musicos. Ruy veio para o Rio de Janeiro em 1958, seu porto seguro até hoje. A vinda ao Brasil era um desejo manifestado anos antes em cartas ao pai, irmão e amigos.</p>
<p class="basico">Tem atualmente (agosto 2014) 83 anos, bem vividos mundo afora e conserva uma energia de dar inveja a gente mais jovem. Muitos dizem que traz essa força de seu país de origem, Moçambique, na África Austral, à beira  do Oceano Indico; é filho de portugueses que foram tentar a vida na colônia e se aclimataram  na capital Lourenço Marques, formando família. Desde seus 10 anos Ruy foi louco por escrever,  louco por cinema e por filmar. Durante a segunda metade dos anos 1940 publicou na imprensa vários contos, artigos e poesias  e até hoje fala constantemente de sua vocação frustrada de escritor, reafirmando o desejo de escrever um romance.</p>
<p class="basico">Desde adolescente  Ruy compreende o fazer cinema como uma forma de pensar e apresentar as relações político-sociais. Lourenço Marques era o porto do Indico mais importante da África Austral  e boa parte do comércio do sul do continente passava por lá. Aos 16 anos, com uma câmara de 8 mm. emprestada por um amigo, filmou a realidade portuária do Cais Gorjão, retratando a vida dos trabalhadores negros. Filmou-os descansando embaixo  de vagões, alimentando-se, dormindo sob trens; para Ruy aquelas imagens  “me lembravam campos de concentração”. Segundo um analista, já como amador Ruy “flertava com a denúncia social”.</p>

<p class="imagem">
	<img class="img480" src="images/ruy_guerra-por_lara.jpg" alt="foto de Ruy Guerra enviada por sua irmã Lara" title="foto de Ruy Guerra enviada por sua irmã Lara" />
	<br class="all" />
	Em Moçambique
</p>

<p class="basico">Na casa paterna e no Liceu Salazar, escola pública que frequentou, Ruy recebeu uma educação luso-europeia. Segundo ele e colegas, foram educados por professores “degredados de Portugal pela Ditadura”, “cabeças pensantes críticas” que os faziam ler muito, o que acabou por tornar muitos deles rebeldes ao status quo. Havia uma certa recusa à produção cultural da ditadura salazarista e o que vinha do Brasil  nessa área era muito importante, não só por que o Brasil era ex-colônia portuguesa que realizara sua independência, mas pelas semelhanças com a cultura e espaço brasileiros ( clima, presença do negro, aromas e sabores ...). A literatura brasileira, revistas, muitas vezes eram censuradas, tendo que entrar por baixo do pano, muito marcantes nessa geração chamada da “diáspora”. Em entrevista Ruy afirma: “Alguns acabaram constituindo uma geração que em sua maioria deixou o país e se distinguiu no campo das artes, filosofia (...) devido ao contexto político e social em que nascemos e fomos criados (...) não por acaso ou por condições psicológicas individuais apenas”. Essa parte de sua geração fez da cultura a via de sua revolta política contra o colonialismo e o racismo. Preocupado   com  as relações de dominação e subordinação na colônia, passou por interrogatórios e detenções feitas pela policia da ditadura  portuguesa em razão de suas atitudes independentes no Liceu, em razões de suas atividades e de seu grupo, acabando por ter um processo que o impediu de voltar a Portugal por alguns anos.</p>
<p class="basico">Aos 20 anos foi estudar cinema  em Paris. Chegou na capital francesa em um momento muito quente para o cinema, pois jovens  cineastas tentavam impor seu cinema de autor contra um cinema da grande indústria tradicional. Formou-se profissionalmente nesse período - inicio dos anos 1950 – em que o cinema tradicional estava sob o impacto de uma renovação, com as primeiras marolas do surgimento da Nouvelle Vague. Rememora o movimento como constituído por jovens intelectuais franceses  dos quais ele, como imigrante estrangeiro, se sentia muito diferente: “ ( a Nouvelle Vague) sempre teve uma marcada posição direitista  e eu (..) tinha uma posição nitidamente de esquerda ... condenava aos intelectuais franceses justamente um apolitismo extremamente político, nunca falavam da guerra da Argélia, nem dos imigrantes”. Cursou o IDHEC (Institut des Hautes Études Cinématographiques), sendo visto por colegas como ótimo aluno, mais preparado que os outros, embora um permanente contestador. Fez ainda por dois anos um curso de ator no Théatre National de Paris (TNP). </p>
<p class="basico">Na capital francesa aproximou-se  de brasileiros com os quais acabou vindo tentar sua chance num Novo Mundo que esperava conquistar através de seu  entusiasmo por seu trabalho.  Trazia na bagagem o primeiro roteiro escrito logo após se formar e que tinha tentado por muitas formas implementar no Velho Mundo, a Europa; roteiro que depois vai se tornar Os Fuzis, Urso de Prata no Festival de Berlim em 1964, um dos filmes mais marcantes desse momento.</p>

<p class="imagem">
	<img class="img800" src="images/cinema-novo_grupo.jpg" alt="cinema novo no Brasil" title="cinema novo no Brasil" />
	<br class="all" />
	Reunião de cineastas para um programa da TV francesa Carnets Brésiliens, Copacabana, 1966
</p>

<p class="basico">Afirma brincando que nasceu cineasta com o Cinema Novo mas não nele, em meio aos jovens entre os quais, apesar das costumeiras rivalidades e choques, havia uma estreita colaboração em função dos filmes que faziam. Era um cinema de busca de identidade: “Estávamos interessados em produzir filmes que retratassem a realidade do povo, os conflitos políticos e sociais, que fugissem  às regras de produção e aos dogmatismos da estética do cinema industrial.” Ruy porém não pratica a arte como arma de propaganda revolucionária; sua filmografia dificilmente poderá ser vista como didática. Foi parte de uma geração que, nos anos 1960, quiz mudar o mundo pelo que acreditava ser o melhor para a sociedade; também, alguns deles e Ruy entre eles, por sua prática de vida. </p>
<p class="basico">Ao longo dos anos, trabalhou em diversas funções ligadas à tela (fotógrafo, assistente de direção, diretor, roteirista, ator, montador, produtor executivo, conselheiro executivo e artístico ou  professor).  Declarou-se  recentemente como “um artista tipicamente produto do subdesenvolvimento”, levado a exercer várias formas de arte para subsistir. Usou  de todos seus dons com a palavra; além da  composição de poemas, letras de músicas, escreveu e dirigiu teatro, e por cinco anos redigiu crônicas semanais para o Caderno Dois do jornal O Estado de S.Paulo. </p>
<p class="basico">Durante certo tempo a viver da escrita de letras de músicas para amigos músicos da zona Sul carioca como Sergio Ricardo, Edu Lobo, Chico Buarque de Holanda, Francis Hime, Carlos Lyra, Luiz Eça e Milton Nascimento. Letrista de mão cheia, fez por volta de 100 letras que abandonavam o teor “o barquinho e a flor” da Bossa Nova por uma temática mais forte, de teor social. A situação complicada para viver de seu cinema o levou também a trabalhar com o teatro.  Dirigiu shows musicais de seus amigos e, quando convidado, algumas peças ao longo dos anos. Ainda para o teatro escreveu em parceria com Chico Buarque “Calabar: o elogio da traição”, peça foi interditada pela c ensura da ditadura militar. Como inúmeros outros,  muitas vezes Chico Buarque e Ruy tiveram diversos problemas com as letras.</p>
<p class="basico">Muitas vezes classificado como cineasta político,  muito se orgulha dessa marca maior. Desde sua adolescência ser político tem para ele um sentido amplo: é estar envolvido com as problemáticas de sua época. Afirma várias vezes:  “Tenho um olhar político sobre a realidade, de um ponto de vista cultural”. Ao longo de sua vida Ruy ostentou esse posicionamento político com P maiúsculo, não tendo sido nunca  um militante ou membro de partido político. Ruy se vê e é visto, como um homem à esquerda  a partir de suas falas, suas atitudes de vida, suas expressões no campo artístico e educacional. Para ele qualquer estética é política, pois traz necessariamente embutida uma visão de mundo, ancorando-se em um conjunto de valores que apresenta, defende ou condena. Em 1997, a analista de cinema M. do Rosário Caetano observou que ele conservava a “retórica sessentista politizadissima” e parecia não acreditar no fim das ideologias; em falas e escritos recentes Ruy parece confirmar essa afirmação. </p>
<p class="basico">Nos anos 1960/70 trabalhou por diversas vezes em França no cinema e para a televisão. Foi bastante ligado ao grupo da revista de cinema Positif. Em 1965 a revista francesa  Cahiers de Cinema – que dava enorme destaque ao Cinema Novo Brasileiro - resume os temas de seus filmes: a crueldade, a violência, o racismo, o tempo que não acaba... Segundo Ruy, “Quem analisa meus filmes já disse que há uma espécie de obsessão pelas áreas de poder e os mecanismos repressivos, seja no ambiente familiar, nas estruturas sociais ou no governo.” </p>
<p class="basico">A  revolução socialista da nova República Popular de Moçambique, vitoriosa em 1975 sob a chefia de Samora Machel, atribuiu em seu início um papel fundamental ao cinema na construção da identidade nacional. Parte importante na tentativa de unir em uma nação diversas tribos, cuja cultura se baseava na tradição oral. Instado por ex-colegas no governo, Ruy passou a colaborar ativamente na criação do Instituto Nacional de Cinema de Moçambique (INC) e na formação de quadros para cinema; dava aulas práticas e trouxe para Maputo (ex Lourenço Marques )muitos especialistas nas mais variadas atividades da área. Viveu intensamente a experiência de independência e descolonização da terra onde nascera; seus filmes africanos são de natureza essencialmente política. </p>
<p class="basico">Sua posição de esquerda fica clara também em suas relações com Cuba, onde viveu por alguns períodos. A partir do aparecimento do Festival Internacional do Novo Cinema Latino-Americano em 1979, seus filmes são lá apresentados. Desde 1988 fez parte do quadro de professores da conhecida "Escuela Internacional de Cine y TV", em San Antonio de Los Baños, a 30 km de Havana. Participou  de projetos e roteiros com aquele que seu tornou seu amigo pessoal: Gabriel García Márquez – o Gabo - um dos fundadores da Escuela. Foi o maior realizador de filmes de Gabo: Erendira, La bela Palomera, Veneno da Madrugada e Me alquilo para Soñar (mini-série para a televisão espanhola, totalmente filmado em Havana). Lá rodou no final dos anos 1990 um filme adaptado de um romance de Chico Buarque, Estorvo, tendo como o personagem principal o ator cubano Jorge Perrugoria e uma equipe formada em boa parte por técnicos cubanos.</p>

<p class="imagem">
	<img class="img800" src="images/com-gabo.jpg" alt="Ruy Guerra com Gabriel García Márquez" title="Ruy Guerra com Gabriel García Márquez" />
	<br class="all" />
	Ruy Guerra e Gabriel García Márquez na filmagem de Erendira, Mexico, 1982
</p>

<p class="basico">Cineastas brasileiros e latino-americanos por vezes ficam décadas sem conseguir filmar, pois  enfrentam dificuldades econômicas permanentes  e por vezes  dificuldades conjunturais em razão do momento político. Ruy conseguiu filmar longas, médias e curtas metragens  no Brasil, na França, em Portugal, na Espanha, no México, em Cuba. Afirma muita vezes :“Não fiz todos os filmes que queria, mas queria fazer todos os filmes que fiz.” No inicio do século XXI é convidado para escrever para o teatro sobre o D Quixote, criando um musical chamado Don Quixote de lugar nenhum, uma adaptação do personagem ao Nordeste brasileiro.</p>
<p class="basico">E quando não pode filmar, ensina, atividade na qual muito se empenhou, organizando cursos de cinema no Rio de Janeiro desde os anos 1990. Suas atividades de professor se desdobraram  nos últimos 10-12 anos em cursos, palestras e oficinas. Em entrevista afirmou: “Digo na primeira aula: Se você vem aqui para fazer filme norte-americano é fácil. Vamos para o bar e em uma hora, eu falo tudo que você precisa saber.´(...) Falo para eles que não vale a pena perder dois anos e meio para fazer filmes como os norte-americanos. Agora, se o cara quer fazer filme brasileiro, ele vai passar dois anos remando na faculdade e vai continuar remando, não sairá da faculdade sabendo não. É outra coisa: é busca, é se vincular à realidade, é saber quem você é”. Ressalta como fundamental “abrir as cabeças dos jovens para o ato de pensar a arte, a formação cultural (...) para que uma pessoa assuma uma responsabilidade tão grande (...) para com esse meio de expressão  que é a meu ver extremamente vital e importante, política e esteticamente importante“.</p>
<p class="basico">Falando sobre filmes e mercado, toma posição clara: “As equações da sociedade estão todas mal feitas e você vive com essas equações equivocadas. Um filme não tem que dar 10 milhões de espectadores. Um filme tem que ser visto por X pessoas que podem tirar desse filme alguma coisa importante para a vida delas. É diferente. Porque desses milhões de espectadores geralmente não tem dez que tirem do filme alguma coisa importante para a vida delas. Elas consumiram aquele filme como um produto, como um ´fast food´. (...) É importante dizer que ver esses filmes norte-americanos é a mesma coisa que frequentar o Macdonald´s. Não tem diferença nenhuma.(...)É preciso cuidado, muito cuidado”.´</p>
<p class="basico">O estudo e a prática de uma linguagem cinematográfica sempre renovada é uma  constante em seu fazer cinema. Destaca como imprescindível essa procura de uma renovação: “Algo fundamental para mim é encontrar estruturas que rompam  com os conceitos padrões, basicamente da estrutura hegemônica norte-americana, que acredito serem redutores da realidade e não servirem para a nossa cultura. (...). Essa recusa, esse fator recusa, acho que está presente ainda hoje. Muitos filmes estão equivocados, mas acho que isso está presente mesmo nesses filmes que estão equivocados.”</p>
<p class="basico">Tem vivido em vários continentes e países, sendo apontado como “um cidadão do mundo”. Seu percurso de vida não se separa de sua produção artística, pois foi a busca dessa mesma o fio condutor de seus deslocamentos no espaço e da continuidade de suas atividades no tempo. Define-se:“meio africano, meio português, meio brasileiro, um tanto latino, meio perdido, 100% o que nesse coquetel de angústias”?</p>

<p class="imagem">
	<img class="img480" src="images/atacama.jpg" alt="Ruy Guerra no deserto do Atacama" title="Ruy Guerra no deserto do Atacama" />
	<br class="all" />
	No deserto do Atacama (Chile, 2014)
</p>
EOT;

}

if ($idioma == 3) {
	include "rodape-eng.inc";
	echo "</section>";
	include "menu-eng.inc";
} elseif ($idioma == 2) {
	include "rodape-fr.inc";
	echo "</section>";
	include "menu-fr.inc";
}	else {
	include "rodape.inc";
	echo "</section>";
	include "menu.inc";
}
?>
</body>
	
